"""Generates the tiny Core ML fixtures used by `clay-depth-selftest`.

    .cache/iqa-env/bin/python tools/make_depth_test_fixtures.py

(any Python with coremltools >= 7 works). Writes
`Sources/clay-depth-selftest/Fixtures.swift`, which embeds each .mlpackage's files as base64
so the self-test exercises the real Core ML load / compile / predict path without any
downloaded model. The fixtures mimic the I/O contracts of the real depth backends:

relative  Like Apple's DepthAnythingV2SmallF16: RGB image input (56 x 42, landscape, like
          518 x 392), Grayscale16Half *image* output. The "depth" is the input's red channel
          scaled to 0-1, so the test can check orientation, letterboxing and output mapping
          pixel by pixel.
pro       Like a converted Depth Pro: square RGB input (48 x 48) normalised to [-1, 1],
          Float16 multi-array `canonical_inverse_depth` (1 x 1 x 48 x 48) and `fov_deg` (1).
          canonical_inverse_depth = 0.25 * (r + 1) + 0.05, fov_deg = 60.
"""

import base64
import pathlib
import tempfile

import coremltools as ct
from coremltools.converters.mil import Builder as mb
from coremltools.proto import FeatureTypes_pb2

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "Sources" / "clay-depth-selftest" / "Fixtures.swift"


def relative_fixture(path: pathlib.Path):
    h, w = 42, 56

    @mb.program(input_specs=[mb.TensorSpec(shape=(1, 3, h, w))], opset_version=ct.target.macOS14)
    def prog(image):
        r = mb.slice_by_index(x=image, begin=[0, 0, 0, 0], end=[1, 1, h, w])
        return mb.cast(x=r, dtype="fp16", name="depth")

    m = ct.convert(prog, inputs=[ct.ImageType(name="image", shape=(1, 3, h, w), color_layout=ct.colorlayout.RGB,
                                              scale=1 / 255.0)],
                   minimum_deployment_target=ct.target.macOS14, compute_precision=ct.precision.FLOAT16)
    spec = m.get_spec()
    out = spec.description.output[0]
    out.type.imageType.width = w
    out.type.imageType.height = h
    out.type.imageType.colorSpace = FeatureTypes_pb2.ImageFeatureType.GRAYSCALE_FLOAT16
    spec.description.metadata.shortDescription = "clay-depth-selftest relative fixture"
    ct.models.MLModel(spec, weights_dir=m.weights_dir).save(str(path))


def pro_fixture(path: pathlib.Path):
    s = 48

    @mb.program(input_specs=[mb.TensorSpec(shape=(1, 3, s, s))], opset_version=ct.target.macOS14)
    def prog(image):
        r = mb.slice_by_index(x=image, begin=[0, 0, 0, 0], end=[1, 1, s, s])
        cid = mb.add(x=mb.mul(x=mb.add(x=r, y=1.0), y=0.25), y=0.05)
        cid16 = mb.cast(x=cid, dtype="fp16", name="canonical_inverse_depth")
        fov = mb.add(x=mb.mul(x=mb.reduce_mean(x=r, axes=[1, 2, 3], keep_dims=False), y=0.0), y=60.0)
        return cid16, mb.cast(x=fov, dtype="fp16", name="fov_deg")

    m = ct.convert(prog, inputs=[ct.ImageType(name="image", shape=(1, 3, s, s), color_layout=ct.colorlayout.RGB,
                                              scale=2 / 255.0, bias=[-1, -1, -1])],
                   minimum_deployment_target=ct.target.macOS14, compute_precision=ct.precision.FLOAT16)
    m.short_description = "clay-depth-selftest Depth Pro-like fixture"
    m.save(str(path))


def swift_literal(name: str, package: pathlib.Path) -> str:
    # Directories are listed too (as "path/": ""): the package manifest refers to the (empty) weights folder.
    lines = [f"    static let {name}: [String: String] = ["]
    for f in sorted(package.rglob("*")):
        rel = f.relative_to(package).as_posix()
        if f.is_dir():
            lines.append(f'        "{rel}/": "",')
        else:
            lines.append(f'        "{rel}": "{base64.b64encode(f.read_bytes()).decode()}",')
    lines.append("    ]")
    return "\n".join(lines)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        relative_fixture(tmp / "relative.mlpackage")
        pro_fixture(tmp / "pro.mlpackage")
        body = "\n\n".join([swift_literal("relative", tmp / "relative.mlpackage"),
                            swift_literal("pro", tmp / "pro.mlpackage")])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by tools/make_depth_test_fixtures.py — do not edit.\n"
        "// Tiny Core ML packages (files as base64) that mimic the depth backends' I/O contracts.\n\n"
        "enum Fixtures {\n" + body + "\n}\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
